#Python Numpy Array

In [0]:
#import numpy package
import numpy as np


In [0]:
#creating arrays from python lists
np.array([1,2,3,5,6])

array([1, 2, 3, 5, 6])

In [0]:
#nested list results in multi dimensional array
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [0]:
#Creating array from scratch
#create a length 10 integer array filled with zeroes
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
#create a 3*2 array filled with 1s
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
#create a 3*5 array filled with 3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [0]:
#create an array filled with a linear sequence starting at 0 stopping at 20 stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
#create an array of five values evenly spaced between o and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [0]:
#create an array of uniformly distributed random values
np.random.random((3,3))

array([[0.8950308 , 0.10614186, 0.92327739],
       [0.18826749, 0.61441432, 0.58633257],
       [0.51184028, 0.37678683, 0.40016073]])

In [0]:
#create an array of normally distributed random values with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.09365706, -0.57344837,  0.47261229],
       [-0.66443322, -1.36708437, -1.99151869],
       [ 0.79634065,  0.88188438, -1.89157916]])

In [0]:
#create an array of random integers in interval [0-10]
np.random.randint(0,10,(3,3))

array([[4, 5, 5],
       [1, 7, 0],
       [1, 9, 8]])

##Array Indexing

In [0]:
np.random.seed(0) #seed for reproducibility
x1= np.random.randint(10,size=6) #1-D array
x2= np.random.randint(10,size=(3,4)) #2-D array

In [0]:
x1

array([5, 0, 3, 3, 7, 9])

In [0]:
x1[0]  #accessing elemnts by indexing

5

In [0]:
#to access index from the end of the array, we can use negative indices
x1[-1]

9

In [0]:
#in multidimensional array we can access item using a comma seperated tuple of indices
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [0]:
x2[0,0]

3

In [0]:
#we can also modify the values
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

##Array Slicing

In [0]:
#The NumPy slicing syntax follows that of the standard Python list; to access a slice of
#an array x, use this:
#x[start:stop:step]
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x[:5] #first five elemnts

array([0, 1, 2, 3, 4])

In [0]:
x[5:] #elemnts after index 5

array([5, 6, 7, 8, 9])

In [0]:
x[4:7] #middle subarray

array([4, 5, 6])

In [0]:
x[::2] #every other elemnt

array([0, 2, 4, 6, 8])

In [0]:
x[1::2] #every other element starting at index 1

array([1, 3, 5, 7, 9])

In [0]:
x[::-1] #all elements reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

##Multidimensional subaaray
it works the same way , with multiple slices seperated by commas

In [0]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [0]:
x2[:2,:3] #two roms, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [0]:
x2[:3,::2] # all rows every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [0]:
#subarray dimension can be reversed together
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

##Accessing arrays rows and columns

In [0]:
print(x2[:,0]) #first column of x2

[12  7  1]


In [0]:
print(x2[0,:]) #first row of x2

[12  5  2  4]


##Subarrays as no copy views

In [0]:
#Array slices return views rather than copy of array datas.
#consider our 2-D array
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [0]:
#extract a 2*2 subarray
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [0]:
#Now if we modify this subarray, we will see original array is  changed
x2_sub[0,0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [0]:
print(x2)   #it is quite usefull when working with large datasets we can access and process pieces of datasets

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [0]:
x2_sub_copy = x2[:2,:2].copy()   #creating a copy of x2
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [0]:
#if we now modify this subaaray original is not changed
x2_sub_copy[0,0] = 99
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [0]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


##Reshaping of arrays

In [0]:
a = np.arange(1,10).reshape(3,3) #numbers 1 to 9 in 3*3 grid
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [0]:
a.reshape(1,3)  #1 row 3 columns

array([[1, 2, 3]])

In [0]:
a.reshape(3,1) #three rows and 1 column

array([[1],
       [2],
       [3]])

##Array concatenation

In [0]:
x= np.array([1,2,3])
y= np.array([3,2,1])
np.concatenate([x,y])  #concatenating/joining two arrays i.e x and y

array([1, 2, 3, 3, 2, 1])

In [0]:
#we can also concatenate more than two arrays at once
z= [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [0]:
#np.concatenate can also be used for 2-D arrays
a= np.array([[1,2,3],
             [4,5,6]])

In [0]:
#concatenate along the first axis
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [0]:
#concatenate along the second axis
np.concatenate([a,a],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [0]:
#for working with with arrays of mixed dimensions, we can use np.vstack and np.hstack
x= np.array([1,2,3])
a=np.array([[9,8,7],
            [6,5,4]])
np.vstack([a,x])  #vertically stack the arrays


array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [0]:
y= np.array([[99],
             [99]])
np.hstack([a,y])    #horizontally stack the arrays

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

##Splitting of arrays

In [0]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 =  np.split(x,[3,5]) #splitting arrays x1 holds values from 0 to 3rd indices, x2 holds values 3 to 5 indices, rest is stored in x3(indices starts with 0)
print(x1,x2,x3)   # N split points leads to N + 1 subaarays

[1 2 3] [99 99] [3 2 1]


In [0]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
upper,lower = np.vsplit(a,[2])  #vertical split from 2nd row
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [0]:
left,right = np.hsplit(a,[2]) #vertical split from 2 columns
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


##Numpy Universal functions

###Array Arithmatic

In [0]:
x= np.arange(4)

In [0]:
print('X = ',x)  #prints value of x

X =  [0 1 2 3]


In [0]:
print('X + 5= ',x+5)  #addition, 5 is added with each element in array

X + 5=  [5 6 7 8]


In [0]:
print('X + 5= ',x+5)  #addition, 5 is added with each element in array

X + 5=  [5 6 7 8]


In [0]:
print('X - 5= ',x-5)  #subtraction, 5 is subtracted with each element in array

X - 5=  [-5 -4 -3 -2]


In [0]:
print("x*2=", x*2)    #multiplication

x*2= [0 2 4 6]


In [0]:
print('x/2=',x/2)    #division

x/2= [0.  0.5 1.  1.5]


In [0]:
print('x//2=', x//2)  #floor devision

x//2= [0 0 1 1]


In [0]:
print('-x=', -x)   #negation

-x= [ 0 -1 -2 -3]


In [0]:
print('x ** 2=', x**2)   #exponentiation

x ** 2= [0 1 4 9]


In [0]:
print('x % 2 = ', x%2)   #modulus

x % 2 =  [0 1 0 1]


In [0]:
#absolute value
x= np.array([-2,-2,0,1,2])
abs(x)   #its gives the absolute values

array([2, 2, 0, 1, 2])

In [0]:
np.absolute(x)

array([2, 2, 0, 1, 2])

In [0]:
np.abs(x)

array([2, 2, 0, 1, 2])

In [0]:
#Exponents
x= [1,2,3]
x

[1, 2, 3]

In [0]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [0]:
np.exp2(x)

array([2., 4., 8.])

In [0]:
np.power(3,x)

array([ 3,  9, 27])

In [0]:
#Logarithms
x= [1,2,4,10]
x

[1, 2, 4, 10]

In [0]:
np.log(x)

array([0.        , 0.69314718, 1.38629436, 2.30258509])

In [0]:
np.log2(x)

array([0.        , 1.        , 2.        , 3.32192809])

In [0]:
np.log10(x)

array([0.        , 0.30103   , 0.60205999, 1.        ])

###Aggregates

In [0]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [0]:
np.add.reduce(x)  #provides the sum of all the elements

15

In [0]:
np.multiply.reduce(x) #product of all array elements

120

In [0]:
np.add.accumulate(x)  #stores the intermediate results

array([ 1,  3,  6, 10, 15])

In [0]:
np.sum(x)    #provides the sum of all the elements

15

In [0]:
np.min(x)  #provides the minimum value in the array

1

In [0]:
np.max(x)  #provides the max value in array

5

In [0]:
#Multidimensional aggregates
M= np.random.random((3,4))
M

array([[0.67887953, 0.72063265, 0.58201979, 0.53737323],
       [0.75861562, 0.10590761, 0.47360042, 0.18633234],
       [0.73691818, 0.21655035, 0.13521817, 0.32414101]])

In [0]:
M.sum()   #it aggregates over the entire array

5.456188913304558

In [0]:
M.min(axis=0)   #column wise aggregation

array([0.67887953, 0.10590761, 0.13521817, 0.18633234])

In [0]:
M.max(axis=1)   #rows wise aggregation

array([0.72063265, 0.75861562, 0.73691818])